# Taken from https://gitlab.com/ft/etc-gnu-toolchain
python
import os
import pathlib
import sys
sys.path.insert(0, os.environ['HOME'] + '/.local/venv/arm-gdb')
print("Importing arm-gdb...")
import arm_gdb
end

