#! /bin/sh

LABEL="${LABEL:-}"

case "$BLOCK_BUTTON" in
    1|2|3)
export TERM=xterm
ROFI_OUT="$(autorandr --detected \
  | $HOME/.local/bin/rofi-context-choice.sh "$(autorandr --current)")"
autorandr --load ${ROFI_OUT}
    esac

echo "$LABEL$(autorandr --current)"
echo "$LABEL$(autorandr --current)"
