# colors in commands
alias ls='ls --color=auto'
alias diff='diff --color=auto'

man() {
  LESS_TERMCAP_md=$'\e[01;31m' \
  LESS_TERMCAP_me=$'\e[0m' \
  LESS_TERMCAP_se=$'\e[0m' \
  LESS_TERMCAP_so=$'\e[01;44;33m' \
  LESS_TERMCAP_ue=$'\e[0m' \
  LESS_TERMCAP_us=$'\e[01;32m' \
  command man "$@"
}

# Starts a gdb session with arm-gdb and cmsis-svd loaded from a python venv.
# This allows for inspection of MCU-specific registers from GDB.
#
# See also:
# - https://github.com/pengi/arm_gdb
# - https://github.com/cmsis-svd/cmsis-svd-data
arm-gdb() {
	GDB_CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/gdb/"
	GDB_VENV="${GDB_VENV:-$HOME/.local/venv/arm-gdb/}"
	GDB_VENV_ACTIVATE="$GDB_VENV/bin/activate"

	if [ -f "$GDB_VENV_ACTIVATE" ]; then
		echo "Activating python venv: '$GDB_VENV'"
		. "$GDB_VENV_ACTIVATE"
		gdb-multiarch \
			--directory="$GDB_CONF_DIR" \
			--eval-command="source cm.conf" \
			"$@"
	else
		echo "No python venv found at '$GDB_VENV'."
		return 1
	fi
}

# no more old vim
alias vim='nvim'
alias nv='nvim'
alias sunv='sudo -E -s nvim'
alias nvsu='sudo -E -s nvim'

# prompt
source ${XDG_CONFIG_HOME:-$HOME/.config}/bash/git-prompt.sh
PS1='\[\e[93m\]\u\[\e[0m\]@\[\e[94m\]\h \[\e[92m\]\w\[\e[91m\]$(__git_ps1) \[\e[m\]\n\$ '

# tmux-sessionizer
source ${XDG_CONFIG_HOME:-$HOME/.config}/bash/tmux-sessionizer.sh

# fzf
if [ -f "/usr/share/doc/fzf/examples/key-bindings.bash" ]; then
	source "/usr/share/doc/fzf/examples/key-bindings.bash"
else
	eval "$(fzf --bash 2>/dev/null)"
fi

# motd
shopt -q login_shell || cat ${XDG_CONFIG_HOME:-$HOME/.config}/bash/motd

# local install location
export PATH="${PATH}:$HOME/.local/bin"

